"""Write every example's README.md and the gallery (examples/README.md) from the `meta.yaml` next to each example.

    python scripts/gen_gallery.py           # write
    python scripts/gen_gallery.py --check   # exit 1 if anything is out of date (CI)

meta.yaml keys: title, summary, needs (extras), keys (env vars), imports (modules the test needs),
offline (false = the test skips it), why (what it needs instead), expect (text the output must contain).
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
EXAMPLES = ROOT / "examples"
CREDIT = (
    "Built on [Laya](https://github.com/NandhaKishorM/laya) (Apache-2.0) by Nandakishor M / Convai Innovations. "
    "decisionsmith is an independent project, not affiliated with TypeSafe AI or Convai Innovations."
)


def scripts(folder: Path) -> list[Path]:
    return sorted(p for p in folder.glob("*.py") if not p.name.startswith("_") and p.name != "schema.py")


def doc(path: Path) -> str:
    text = ast.get_docstring(ast.parse(path.read_text())) or ""
    return text.strip().splitlines()[0] if text.strip() else ""


def group_title(name: str) -> str:
    return name.split("-", 1)[-1].replace("-", " ").capitalize()


def readme(folder: Path, meta: dict) -> str:
    rel = folder.relative_to(ROOT).as_posix()
    files = scripts(folder)
    title = meta.get("title") or folder.name.replace("-", " ").capitalize()
    lines = ["# %s" % title, "", meta.get("summary", ""), ""]
    main = folder / "main.py" if (folder / "main.py").exists() else files[0]
    lines += ["```python", main.read_text().rstrip(), "```", ""]
    if len(files) > 1:
        lines += ["| file | what it shows |", "|---|---|"]
        lines += ["| [`%s`](%s) | %s |" % (p.name, p.name, doc(p)) for p in files]
        lines.append("")
    lines += ["## Run", "", "```bash"]
    needs = meta.get("needs") or []
    lines.append('pip install "decisionsmith%s"' % ("[%s]" % ",".join(needs) if needs else ""))
    lines += ["pip install %s" % " ".join(meta["pip"])] if meta.get("pip") else []
    lines += ["export %s=..." % k for k in meta.get("keys") or []]
    lines += ["python %s/%s" % (rel, p.name) for p in files]
    lines += ["```", ""]
    if meta.get("offline") is False:
        lines += ["Needs %s to run for real." % meta.get("why", "outside resources"), ""]
    else:
        lines += [
            "No keys yet? `DS_OFFLINE=1` swaps every LLM for a local stand-in so you can walk through the flow.",
            "",
        ]
    lines += ["---", "", CREDIT, ""]
    return "\n".join(lines)


def gallery(entries: list[tuple[Path, dict]]) -> str:
    lines = [
        "# Examples",
        "",
        "Every example is a short runnable script with synthetic data. Each folder has a README with the code and how",
        "to run it. `DS_OFFLINE=1` runs any of them without keys or network (LLM answers come from a local stand-in),",
        "which is also how CI runs every one of them.",
        "",
        "This page is generated by `scripts/gen_gallery.py` from each folder's `meta.yaml`.",
        "",
    ]
    groups: dict[str, list[tuple[Path, dict]]] = {}
    for folder, meta in entries:
        groups.setdefault(folder.relative_to(EXAMPLES).parts[0], []).append((folder, meta))
    for group in sorted(groups):
        lines += ["## %s" % group_title(group), "", "| example | what it shows | needs |", "|---|---|---|"]
        for folder, meta in groups[group]:
            rel = folder.relative_to(EXAMPLES).as_posix()
            title = meta.get("title") or folder.name
            needs = ", ".join(["`%s`" % n for n in meta.get("needs") or []] + list(meta.get("keys") or []))
            lines.append("| [%s](%s/) | %s | %s |" % (title, rel, meta.get("summary", ""), needs or "none"))
        lines.append("")
    lines += ["---", "", CREDIT, ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true")
    args = p.parse_args(argv)
    entries = [(m.parent, yaml.safe_load(m.read_text()) or {}) for m in sorted(EXAMPLES.rglob("meta.yaml"))]
    outputs = {folder / "README.md": readme(folder, meta) for folder, meta in entries}
    outputs[EXAMPLES / "README.md"] = gallery(entries)
    stale = [path for path, text in outputs.items() if not path.exists() or path.read_text() != text]
    if args.check:
        for path in stale:
            print("out of date: %s (run python scripts/gen_gallery.py)" % path.relative_to(ROOT))
        return 1 if stale else 0
    for path in stale:
        path.write_text(outputs[path])
    print("wrote %d files (%d examples)" % (len(stale), len(entries)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
